version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    environment:
      - TZ=Asia/Yekaterinburg
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./example.crt:/etc/nginx/ssl/example.crt
      - ./example.key:/etc/nginx/ssl/example.key
    ports:
      - 80:80
      - 443:443

  app1:
    build:
      context: .
      dockerfile: Dockerfile-app1
    container_name: app1
    environment:
      - TZ=Asia/Yekaterinburg
      - PYTHONUNBUFFERED=1

  app2:
    build:
      context: .
      dockerfile: Dockerfile-app2
    container_name: app2
    environment:
      - TZ=Asia/Yekaterinburg
      - PYTHONUNBUFFERED=1
